- name: removing existing script CE
  file:
    path: /tmp/script_CE.deb.sh
    state: absent

- name: removing existing script multi_runner
  file:
    path: /tmp/script_multi_runner.deb.sh
    state: absent

- name: download script Gitlab CE
  get_url:
     url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
     dest: /tmp/script_CE.deb.sh
     mode: 0777
  run_once: true

- name: execute script Gitlab CE
  command: /tmp/script_CE.deb.sh
  args:
    removes: /tmp/script_CE.deb.sh
  run_once: true

- name: download runner Gitlab CI
  get_url:
     url: https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh
     dest:  /tmp/script_multi_runner.deb.sh
     mode: 0777
  run_once: true

- name: execute script Gitlab multi runner
  command: /tmp/script_multi_runner.sh
  args:
    removes: /tmp/script_multi_runner.sh
  run_once: true

- name: install GitLab runner
  apt:
    name: gitlab-ci-multi-runner
    state: latest
    update_cache: yes
  run_once: true